spring:
  application:
    name: spacestudyship
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # Flyway (공통)
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false

server:
  port: 8080

# Swagger (공통)
springdoc:
  swagger-ui:
    path: /docs/swagger
    display-request-duration: true
    persist-authorization: true
    filter: true
  api-docs:
    path: /docs/api-docs
  packages-to-scan: com.elipair.spacestudyship
  paths-to-match: /api/**

# Actuator (공통)
management:
  endpoints:
    web:
      exposure:
        include: health
