-- members baseline: ddl-auto=update로 이미 생성되어 있을 수 있어 IF NOT EXISTS 사용
CREATE TABLE IF NOT EXISTS members (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_id    VARCHAR(100) NOT NULL,
    social_type  VARCHAR(10)  NOT NULL,
    nickname     VARCHAR(30)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    CONSTRAINT uk_members_social_id_type UNIQUE (social_id, social_type),
    CONSTRAINT uk_members_nickname UNIQUE (nickname)
);

-- user_devices: 디바이스별 인증 세션 + FCM 토큰
CREATE TABLE IF NOT EXISTS user_devices (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id     BIGINT       NOT NULL,
    device_id     VARCHAR(255) NOT NULL,
    device_type   VARCHAR(10)  NOT NULL,
    fcm_token     VARCHAR(255) NOT NULL,
    refresh_token VARCHAR(512) NOT NULL,
    last_login_at TIMESTAMP    NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_user_devices_member_device UNIQUE (member_id, device_id),
    CONSTRAINT fk_user_devices_member FOREIGN KEY (member_id)
        REFERENCES members(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_devices_member ON user_devices(member_id);
