-- exploration_nodes: 행성/지역 마스터 (시드, 읽기 전용)
CREATE TABLE IF NOT EXISTS exploration_nodes (
    id                    VARCHAR(50)  PRIMARY KEY,
    name                  VARCHAR(50)  NOT NULL,
    node_type             VARCHAR(10)  NOT NULL,
    depth                 INTEGER      NOT NULL,
    icon                  VARCHAR(30)  NOT NULL,
    parent_id             VARCHAR(50),
    prerequisite_node_id  VARCHAR(50),
    required_fuel         INTEGER      NOT NULL DEFAULT 0,
    sort_order            INTEGER      NOT NULL DEFAULT 0,
    description           VARCHAR(200) NOT NULL DEFAULT '',
    map_x                 DOUBLE PRECISION NOT NULL DEFAULT 0,
    map_y                 DOUBLE PRECISION NOT NULL DEFAULT 0,
    CONSTRAINT fk_expl_node_parent       FOREIGN KEY (parent_id)            REFERENCES exploration_nodes(id),
    CONSTRAINT fk_expl_node_prerequisite FOREIGN KEY (prerequisite_node_id) REFERENCES exploration_nodes(id),
    CONSTRAINT chk_expl_node_type CHECK (node_type IN ('planet','region')),
    CONSTRAINT chk_expl_required_fuel_non_negative CHECK (required_fuel >= 0)
);

-- user_exploration_progress: 유저별 해금 상태 (행 존재 = 해금)
CREATE TABLE IF NOT EXISTS user_exploration_progress (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    node_id      VARCHAR(50)  NOT NULL,
    is_unlocked  BOOLEAN      NOT NULL DEFAULT TRUE,
    is_cleared   BOOLEAN      NOT NULL DEFAULT FALSE,
    unlocked_at  TIMESTAMP    NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    CONSTRAINT fk_user_expl_member FOREIGN KEY (user_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_expl_node   FOREIGN KEY (node_id) REFERENCES exploration_nodes(id),
    CONSTRAINT uq_user_expl UNIQUE (user_id, node_id)
);

CREATE INDEX IF NOT EXISTS idx_user_expl_user ON user_exploration_progress (user_id);

-- 시드: 행성 8 (행성 먼저)
INSERT INTO exploration_nodes (id, name, node_type, depth, icon, parent_id, prerequisite_node_id, required_fuel, sort_order, description, map_x, map_y) VALUES
 ('earth',   '지구',   'planet', 2, 'earth',   NULL, NULL,      0,  0, '우리의 출발지, 고향 행성',        0.5,  0.08),
 ('mercury', '수성',   'planet', 2, 'mercury', NULL, 'earth',   3,  1, '태양에 가장 가까운 작은 행성',     0.15, 0.20),
 ('venus',   '금성',   'planet', 2, 'venus',   NULL, 'mercury', 5,  2, '두꺼운 대기로 뒤덮인 뜨거운 행성', 0.75, 0.32),
 ('mars',    '화성',   'planet', 2, 'mars',    NULL, 'venus',   10, 3, '붉은 행성, 탐험의 꿈',            0.25, 0.44),
 ('jupiter', '목성',   'planet', 2, 'jupiter', NULL, 'mars',    20, 4, '태양계 최대의 가스 행성',          0.7,  0.56),
 ('saturn',  '토성',   'planet', 2, 'saturn',  NULL, 'jupiter', 30, 5, '아름다운 고리를 가진 행성',        0.2,  0.68),
 ('uranus',  '천왕성', 'planet', 2, 'uranus',  NULL, 'saturn',  45, 6, '옆으로 누워 자전하는 얼음 행성',   0.8,  0.80),
 ('neptune', '해왕성', 'planet', 2, 'neptune', NULL, 'uranus',  60, 7, '태양계 끝자락의 푸른 행성',        0.35, 0.92)
ON CONFLICT (id) DO NOTHING;

-- 시드: 지역 30 (지구 12 + 그 외 18). region은 prerequisite NULL, map 0/0.
INSERT INTO exploration_nodes (id, name, node_type, depth, icon, parent_id, prerequisite_node_id, required_fuel, sort_order, description, map_x, map_y) VALUES
 ('korea',     '대한민국', 'region', 3, 'KR', 'earth', NULL, 0,  0, '한반도 남쪽, K-컬쳐의 중심', 0, 0),
 ('japan',     '일본',     'region', 3, 'JP', 'earth', NULL, 1,  1, '벚꽃과 기술의 나라',         0, 0),
 ('thailand',  '태국',     'region', 3, 'TH', 'earth', NULL, 1,  2, '미소의 나라, 동남아의 허브', 0, 0),
 ('china',     '중국',     'region', 3, 'CN', 'earth', NULL, 2,  3, '세계 최대 인구 대국',        0, 0),
 ('india',     '인도',     'region', 3, 'IN', 'earth', NULL, 2,  4, 'IT 강국, 다양한 문화의 보고', 0, 0),
 ('uk',        '영국',     'region', 3, 'GB', 'earth', NULL, 2,  5, '해가 지지 않는 나라',        0, 0),
 ('france',    '프랑스',   'region', 3, 'FR', 'earth', NULL, 2,  6, '예술과 낭만의 나라',         0, 0),
 ('canada',    '캐나다',   'region', 3, 'CA', 'earth', NULL, 2,  7, '단풍과 자연의 나라',         0, 0),
 ('usa',       '미국',     'region', 3, 'US', 'earth', NULL, 3,  8, '자유의 나라, 기회의 땅',     0, 0),
 ('brazil',    '브라질',   'region', 3, 'BR', 'earth', NULL, 3,  9, '삼바와 축구의 나라',         0, 0),
 ('australia', '호주',     'region', 3, 'AU', 'earth', NULL, 3, 10, '코알라와 캥거루의 대륙',     0, 0),
 ('egypt',     '이집트',   'region', 3, 'EG', 'earth', NULL, 2, 11, '피라미드와 나일강의 나라',   0, 0),
 ('mercury_caloris',   '칼로리스 분지', 'region', 3, 'mercury', 'mercury', NULL, 1, 0, '수성 최대의 충돌 분지',           0, 0),
 ('mercury_plains',    '북극 평원',     'region', 3, 'mercury', 'mercury', NULL, 2, 1, '얼음이 숨겨진 영구 그림자 지대',   0, 0),
 ('venus_ishtar',      '이슈타르 대지', 'region', 3, 'venus',   'venus',   NULL, 2, 0, '금성 북반구의 거대한 고원 지대',   0, 0),
 ('venus_aphrodite',   '아프로디테 대지','region', 3, 'venus',   'venus',   NULL, 3, 1, '금성 적도를 따라 펼쳐진 최대 대지', 0, 0),
 ('venus_maxwell',     '맥스웰 산',     'region', 3, 'venus',   'venus',   NULL, 3, 2, '금성에서 가장 높은 산맥',         0, 0),
 ('mars_olympus',      '올림푸스 산',   'region', 3, 'mars',    'mars',    NULL, 3, 0, '태양계에서 가장 높은 화산',        0, 0),
 ('mars_valles',       '마리너 계곡',   'region', 3, 'mars',    'mars',    NULL, 4, 1, '태양계 최대의 협곡',             0, 0),
 ('mars_polar',        '극관 지대',     'region', 3, 'mars',    'mars',    NULL, 5, 2, '드라이아이스와 물 얼음의 극지방',  0, 0),
 ('jupiter_red_spot',  '대적점',        'region', 3, 'jupiter', 'jupiter', NULL, 5, 0, '수백 년간 지속되는 거대 폭풍',     0, 0),
 ('jupiter_europa',    '유로파',        'region', 3, 'jupiter', 'jupiter', NULL, 7, 1, '얼음 아래 바다가 있는 위성',       0, 0),
 ('jupiter_io',        '이오',          'region', 3, 'jupiter', 'jupiter', NULL, 8, 2, '화산 활동이 가장 활발한 위성',     0, 0),
 ('saturn_rings',      '토성 고리',     'region', 3, 'saturn',  'saturn',  NULL, 8, 0, '얼음과 먼지로 이루어진 아름다운 고리', 0, 0),
 ('saturn_titan',      '타이탄',        'region', 3, 'saturn',  'saturn',  NULL, 10, 1, '대기를 가진 유일한 위성, 메탄의 호수', 0, 0),
 ('saturn_enceladus',  '엔셀라두스',    'region', 3, 'saturn',  'saturn',  NULL, 12, 2, '간헐천이 분출하는 얼음 위성',     0, 0),
 ('uranus_miranda',    '미란다',        'region', 3, 'uranus',  'uranus',  NULL, 12, 0, '기괴한 지형의 작은 위성',         0, 0),
 ('uranus_atmosphere', '천왕성 대기',   'region', 3, 'uranus',  'uranus',  NULL, 15, 1, '메탄이 만드는 청록빛 대기',       0, 0),
 ('neptune_dark_spot', '대흑점',        'region', 3, 'neptune', 'neptune', NULL, 15, 0, '초속 2000km 폭풍의 소용돌이',     0, 0),
 ('neptune_triton',    '트리톤',        'region', 3, 'neptune', 'neptune', NULL, 20, 1, '역행 궤도를 도는 거대 위성',       0, 0)
ON CONFLICT (id) DO NOTHING;
